# Generated by Django 3.0.1 on 2019-12-21 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compensationapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturegroup',
            name='semester',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
