# Generated by Django 3.0 on 2019-12-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compensationapp', '0003_auto_20191221_2254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursemeeting',
            name='lecture_group',
        ),
        migrations.AddField(
            model_name='coursemeeting',
            name='lecture_group',
            field=models.ManyToManyField(to='compensationapp.LectureGroup'),
        ),
    ]
